agent_name: autonomous_agent
author: charil
version: 0.1.0
license: Apache-2.0
description: An autonomous agent example with reactive and proactive behaviors.
aea_version: '>=1.0.0, <2.0.0'
fingerprint:
  README.md: bafybeifzdekpjcas6egpwxj24tir5ozzffmkq5ecyi6rw3i6fqfd763etu
  __init__.py: bafybeiehvk4wlv2bcbplwc66owg4qdnisiihijq7iegcmjjxtz3dulnrgm
  tests/__init__.py: bafybeiasj5kqyvalbnedototb6ooxfnro3vjmgscja2iccccotfjnd6cha
  tests/test_autonomous_agent.py: bafybeifbgqpywtwhk6n4wngdrrk3oujwqw3fsbk54gsw5sep3pkkgym2ue
fingerprint_ignore_patterns: []
connections:
- charil/abci:0.1.0:bafybeicidr6u3w4vbalvrsfo4xraptxuti7cyrjlvqqn7udekxpm5hnho4
- charil/http_client:0.1.0:bafybeihi772xgzpqeipp3fhmvpct4y6e6tpjp4sogwqrnf3wqspgeilg4u
- charil/ipfs:0.1.0:bafybeigcijdbwgdekow5c2ikeltetoteabfp52ewy3xfkd7ygaqbl7j3ke
- charil/ledger:0.1.0:bafybeig7woeog4srdby75hpjkmx4rhpkzncbf4h2pm5r6varsp26pf2uhu
- charil/p2p_libp2p_client:0.1.0:bafybeid3xg5k2ol5adflqloy75ibgljmol6xsvzvezebsg7oudxeeolz7e
contracts: []
protocols:
- open_aea/signing:1.0.0:bafybeihv62fim3wl2bayavfcg3u5e5cxu3b7brtu4cn5xoxd6lqwachasi
- charil/abci:0.1.0:bafybeiaqmp7kocbfdboksayeqhkbrynvlfzsx4uy4x6nohywnmaig4an7u
- charil/http:0.1.0:bafybeifugzl63kfdmwrxwphrnrhj7bn6iruxieme3a4ntzejf6kmtuwmae
- charil/ipfs:0.1.0:bafybeiftxi2qhreewgsc5wevogi7yc5g6hbcbo4uiuaibauhv3nhfcdtvm
skills:
- charil/abstract_abci:0.1.0:bafybeicr24cgdovqdp4bh25bpun77v7u33maydwuxwled3tuhyiaepw5gu
- charil/abstract_round_abci:0.1.0:bafybeia6lemk5s64f26qjnd2746s5mufpzxuaf5frsqhfbr62kk3ma6sp4
- charil/autonomous_agent_abci:0.1.0:bafybeiebittgfcz4idj633fkrvu6qle2ajekdjxpp7slggyur7vv7s7hrq
default_ledger: ethereum
required_ledgers:
- ethereum
default_routing: {}
connection_private_key_paths: {}
private_key_paths: {}
logging_config:
  version: 1
  disable_existing_loggers: false
  formatters:
    standard:
      format: '[%(asctime)s] [%(levelname)s] %(message)s'
  handlers:
    logfile:
      class: logging.FileHandler
      formatter: standard
      filename: ${LOG_FILE:str:log.txt}
      level: INFO
    console:
      class: logging.StreamHandler
      formatter: standard
      stream: ext://sys.stdout
  loggers:
    aea:
      handlers:
      - logfile
      - console
      propagate: true
dependencies:
  open-aea-ledger-ethereum:
    version: ==1.53.0
  open-aea-test-autonomy:
    version: ==0.15.0
default_connection: null
---
public_id: charil/autonomous_agent_abci:0.1.0
type: skill
models:
  benchmark_tool:
    args:
      log_dir: ${LOG_DIR:str:/benchmarks}
  params:
    args:
      autonomous_message: ${AUTONOMOUS_MESSAGE:str:Hello, this is Autonomous Agent!}
      reset_pause_duration: ${RESET_PAUSE_DURATION:int:5}
      service_registry_address: ${SERVICE_REGISTRY_ADDRESS:str:null}
      share_tm_config_on_startup: ${SHARE_TM_CONFIG_ON_STARTUP:bool:false}
      on_chain_service_id: ${ON_CHAIN_SERVICE_ID:int:null}
      setup:
        all_participants: ${ALL_PARTICIPANTS:list:[]}
        safe_contract_address: ${SAFE_CONTRACT_ADDRESS:str:'0x0000000000000000000000000000000000000000'}
        consensus_threshold: ${CONSENSUS_THRESHOLD:int:null}
      tendermint_url: ${TENDERMINT_URL:str:http://localhost:26657}
      tendermint_com_url: ${TENDERMINT_COM_URL:str:http://localhost:8080}
      tendermint_p2p_url: ${TENDERMINT_P2P_URL:str:localhost:26656}
---
public_id: charil/abci:0.1.0
type: connection
config:
  target_skill_id: charil/autonomous_agent_abci:0.1.0
  host: ${HOST:str:localhost}
  port: ${PORT:int:26658}
  use_tendermint: ${USE_TENDERMINT:bool:false}
---
public_id: charil/ledger:0.1.0
type: connection
config:
  ledger_apis:
    ethereum:
      address: ${LEDGER_RPC:str:http://localhost:8545}
      chain_id: ${CHAIN_ID:int:31337}
      poa_chain: ${IS_POA_CHAIN:bool:false}
      default_gas_price_strategy: ${DEFAULT_GAS_PRICE_STRATEGY:str:eip1559}
---
public_id: charil/p2p_libp2p_client:0.1.0
type: connection
config:
  nodes:
  - uri: ${NODE_URI_1:str:acn.staging.autonolas.tech:9005}
    public_key: ${NODE_PUB_KEY_1:str:02d3a830c9d6ea1ae91936951430dee11f4662f33118b02190693be835359a9d77}
  - uri: ${NODE_URI_2:str:acn.staging.autonolas.tech:9006}
    public_key: ${NODE_PUB_KEY_2:str:02e741c62d706e1dcf6986bf37fa74b98681bc32669623ac9ee6ff72488d4f59e8}
cert_requests:
- identifier: acn
  ledger_id: ethereum
  message_format: '{public_key}'
  not_after: '2025-01-01'
  not_before: '2024-01-01'
  public_key: ${CERT_PUB_KEY_1:str:02d3a830c9d6ea1ae91936951430dee11f4662f33118b02190693be835359a9d77}
  save_path: .certs/acn_cosmos_9005.txt
- identifier: acn
  ledger_id: ethereum
  message_format: '{public_key}'
  not_after: '2025-01-01'
  not_before: '2024-01-01'
  public_key: ${CERT_PUB_KEY_2:str:02e741c62d706e1dcf6986bf37fa74b98681bc32669623ac9ee6ff72488d4f59e8}
  save_path: .certs/acn_cosmos_9006.txt
is_abstract: true
